---
- name: Ensure dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

# fix repo priority for debian 12
# debian 12 for Skaleet comes with a debian-security repo that contains a superior version of nodejs
# So we enforce the use of nodesource repo
- name: Pin nodejs repo
  copy:
    dest: "/etc/apt/preferences.d/nodejs"
    content: |
      Package: nodejs
      Pin: origin "deb.nodesource.com"
      Pin-Priority: 990
  when: ansible_distribution | lower == "debian" and ansible_distribution_major_version is version('12', '==')

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo is changed
  tags: ['skip_ansible_lint']

# We don't specify version because if we do, the repo priority configured above is not respected.
# We just install the latest version available in the nodesource repo
- name: Ensure Node.js and npm are installed.
  apt:
    name: nodejs
    state: present
  when: ansible_distribution | lower == "debian" and ansible_distribution_major_version is version('12', '==')

- name: Ensure Node.js and npm are installed.
  ansible.builtin.apt:
    name: "nodejs={{ nodejs_version | regex_replace('x', '') }}*"
    state: present
  when: ansible_distribution | lower == "debian" and ansible_distribution_major_version is version('12', '<')
