---
- name: Ensure dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present


- name: Add NodeSource repositories for Node.js.
  deb822_repository:
    name: nodesource_{{ nodejs_version }}
    uris: "https://deb.nodesource.com/node_{{ nodejs_version }}"
    types:
      - deb
      - deb-src
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    state: present
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo is changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  apt:
    name: "nodejs={{ nodejs_version | regex_replace('x', '') }}*"
    state: present
